### PR TITLE
Old name

### PR DESCRIPTION
**Pull request by kmoussai**

### CODE REVIEW

**Comment by msidqi** [comment]
please make sure to remove the empty new line.

hint: double space at the EOL :)

**Comment by oxidia** [comment]
I think this is inaccurate, we was "khodam lyahod" but not anymore!!

**Comment by msidqi** [comment]
Thanks for the suggestion, we'll take it into consideration for future iterations

**Comment by kmoussai** [comment]
This repo is to keep track of all names that have been used in !SC. at least that what I thought.

**Pull request closed without merging**
